- hosts: kubernetes
  become: false
  tasks:
    - name: Deploying blue deployment
      command: kubectl apply -f /home/akshay/Kubernetes/blue-green/blue-deployment.yml
    
    - name: Deploying green deployment
      command: kubectl apply -f /home/akshay/Kubernetes/blue-green/green-deployment.yml

