apiVersion: apps/v1
kind: Deployment
metadata:
  name: green
spec:
  replicas: 1
  selector:
    app: green
  template:
    metadata:
      name: green
      labels:
        app: green
    spec:
      containers:
      - name: green
        image: akshayraina/nginx-green-deployment:v1
        resources: 
          requests: 
            memory: "64Mi"
            cpu: "250m"
          limits: 
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 80